version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpserver
      - postgresql
    networks:
      - laravel

  phpserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpserver
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    links:
      - postgresql
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=postgresql"

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: laravel
      POSTGRES_PASSWORD: postgres
    ports:
      - 5400:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  db-data:
